---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.1.0

jobs:
  test:
    docker:
      - image: circleci/golang:1.12

    steps:
      - prometheus/setup_environment
      - run: make style build
      - prometheus/store_artifact:
          file: pactbroker_exporter

  publish_master:
    description: Build and publish container images from the master branch.
    docker:
      - image: circleci/golang:1.12
    steps:
      - prometheus/setup_build_environment
      - prometheus/publish_images:
          login_variable: REGISTRY_USER
          organization: containersol
          password_variable: REGISTRY_PASS
          registry: docker.io

  publish_release:
    description: Build and publish binaries and container images for a given release tag.
    docker:
      - image: circleci/golang:1.12
    steps:
      - prometheus/setup_build_environment
      - run: promu crossbuild tarballs
      - run: promu checksum .tarballs
      - run: promu release .tarballs
      - store_artifacts:
          destination: releases
          path: .tarballs
      - prometheus/publish_release_images:
          login_variable: REGISTRY_USER
          organization: containersol
          password_variable: REGISTRY_PASS
          registry: docker.io

workflows:
  version: 2
  pact_exporter:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - prometheus/build:
          name: build
          filters:
            tags:
              only: /.*/
      - publish_master:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - publish_release:
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
